# Generated by Django 3.1 on 2020-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npsat_manager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelrun',
            name='n_years',
        ),
        migrations.AddField(
            model_name='modelrun',
            name='sim_end_year',
            field=models.IntegerField(blank=True, default=2300),
        ),
    ]
